bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Adrian Janucik
  description: Analysis of methylation data from Illumina arrays. Perform data pre-processing,
    quality checks, confounder check and finds DMPs (differentially methylated positions)
    and DMRs (differentially methylated regions). Optionally estimate cell type composition
    and adjust data for it.
  force: false
  is_nfcore: true
  name: methylarray
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
