name: nf-core-methylarray
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-minfi=1.48.0
  - bioconductor-illuminahumanmethylationepicv2anno.20a1.hg38=1.0.0
  - bioconductor-illuminahumanmethylationepicv2manifest=1.0.0
  - r-readr=2.1.5
  - r-optparse=1.7.5
  - r-base=4.4.0
