name: density_plots
description: Plot beta-value density distributions before and after SeSAMe normalisation to assess data quality and normalisation effectiveness.
keywords:
  - methylation
  - epigenetics
  - array
  - qc
  - density
  - normalization
  - minfi
input:
  - - name: rg_rds
      type: file
      description: Filtered RGChannelSet object serialised as RDS.
      pattern: "*.rds"
  - - name: beta_norm_rds
      type: file
      description: SeSAMe-normalised beta-value matrix serialised as RDS.
      pattern: "*.rds"
output:
  - - name: density_raw_plot
      type: file
      description: PNG density plot of raw beta values.
      pattern: "06_density_beta_raw.png"
  - - name: density_sesame_plot
      type: file
      description: PNG density plot of SeSAMe-normalised beta values.
      pattern: "07_density_beta_sesame.png"
  - - name: versions
      type: file
      description: File containing software versions.
      pattern: "versions.yml"
authors:
  - "@nf-core"
maintainers:
  - "@nf-core"
args_id: "$args"
